const { DynamoDBClient } = require('@aws-sdk/client-dynamodb');
const { DynamoDBDocumentClient, PutCommand } = require('@aws-sdk/lib-dynamodb');
const { CognitoIdentityProviderClient, AdminCreateUserCommand, AdminAddUserToGroupCommand, AdminDeleteUserCommand } = require('@aws-sdk/client-cognito-identity-provider');
const { randomUUID, randomBytes } = require('node:crypto');
const { resolveHouseholdCode } = require('./households');
const { requireAdmin } = require('./access');
const { logAction } = require('./auditLogger');
const docClient = DynamoDBDocumentClient.from(new DynamoDBClient({}), { marshallOptions: { removeUndefinedValues: true } });
const cognitoClient = new CognitoIdentityProviderClient({});
const USER_POOL_ID = process.env.USER_POOL_ID || 'ca-central-1_dBeo5yZXq';
exports.handler = async event => {
  requireAdmin(event);
  const input = event.arguments.input;
  if (input.householdId !== undefined || input.residentCode !== undefined) throw new Error('Resident codes are generated by the system');
  const email = String(input.email || '').trim().toLowerCase();
  if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) throw new Error('Invalid email format');
  for (const field of ['building', 'floor', 'unitNumber', 'plate']) {
    if (!String(input[field] || '').trim()) throw new Error(`${field} is required`);
  }
  const householdId = await resolveHouseholdCode(docClient, input);
  const id = `resident_${randomUUID()}`;
  const tempPassword = `Aa1!${randomBytes(18).toString('base64url')}`;
  let username;
  let committed = false;
  try {
    const created = await cognitoClient.send(new AdminCreateUserCommand({
      UserPoolId: USER_POOL_ID, Username: email, MessageAction: 'SUPPRESS', TemporaryPassword: tempPassword,
      UserAttributes: [{ Name: 'email', Value: email }, { Name: 'email_verified', Value: 'true' }],
    }));
    username = created.User.Username;
    const userId = created.User.Attributes?.find(a => a.Name === 'sub')?.Value;
    if (!userId) throw new Error('Cognito did not return a user subject');
    await cognitoClient.send(new AdminAddUserToGroupCommand({ UserPoolId: USER_POOL_ID, Username: username, GroupName: 'RESIDENT' }));
    const now = new Date().toISOString();
    const resident = {
      id, email, name: input.name || '', phone: input.phone || '',
      building: input.building.trim(), floor: input.floor.trim(), unitNumber: input.unitNumber.trim(), plate: input.plate.trim().toUpperCase(),
      householdId, residentCode: householdId, userId, cognitoUsername: username, createdAt: now, updatedAt: now,
    };
    await docClient.send(new PutCommand({ TableName: process.env.RESIDENT_TABLE || 'Resident', Item: resident, ConditionExpression: 'attribute_not_exists(id)' }));
    committed = true;
    await logAction('CREATE_RESIDENT', event.identity?.sub, { householdId }, 'Resident', id);
    return { ...resident, tempPassword, message: 'Resident created successfully' };
  } catch (error) {
    if (username && !committed) {
      try { await cognitoClient.send(new AdminDeleteUserCommand({ UserPoolId: USER_POOL_ID, Username: username })); }
      catch (rollbackError) { console.error('Cognito rollback failed', rollbackError.name); }
    }
    throw error;
  }
};
